feat: replace lib imports by importlib
mtth/hdfs pull request #192
Opened 2022-12-29 16:22 UTC by Andromelus

Goal: fix #191 
I am using an alternate laptop for this and cannot run the tests. 😞

2023-01-02 17:23 UTC, tjni commented
I was looking at this too and noticed that `importlib` is not available in Python 2.7 so the import needs to be conditional if that version still needs to be supported.

**Disclaimer:** I'm not affiliated with this project so can't facilitate this getting in.

2023-01-03 07:08 UTC, Andromelus commented
@tjni Indeed, that may be usefull. I'll have a look into it this week.

Concerning the build fail, checking on Internet, seems like Python 3.6 is not available for the latest version of Ubuntu.

2023-02-20 14:52 UTC, Andromelus commented
@tjni The test framework only supports Python 3, not bellow. Therefore I will keep the tests on python 3.6 and 3.12.

2023-08-02 18:00 UTC, mtth requested changes
Thank you for the PR @Andromelus and apologies for the very belated review. This `importlib` change sounds good. A few comments inline.

2023-08-02 18:00 UTC, mtth commented on CHANGES
> +
These are useful to maintainers but not end users, let's omit for now. We can advertise 3.12 support once it's tested in CI.

2023-08-02 18:00 UTC, mtth commented on hdfs/config.py
> +  # Bellow python 3.12
Typo in "below" and "Python" (should be capitalized). Same in `test_examples.py`.

2023-08-08 16:07 UTC, mtth approved these changes
Thanks for the update @Andromelus, looks good.

2023-08-08 16:07 UTC, merged

2023-08-09 15:07 UTC, musicinmybrain commented
This is still broken; there is no `importlib.load_source` in Python 3.12 either. One other project handled it like this: https://github.com/return42/fspath/commit/f09288e1cb0744b760d2221efa670af2eb17e927